---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: applications
spec:
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image:  leonardomkoehler/app-demo:8 
        resources:
          requests: 
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo
  namespace: applications
spec:
  selector:
    app: app-demo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo
  namespace: applications
  labels:
    name: app-demo
spec:
  rules:
  - host: app-demo.koehlerlabs.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-demo
            port: 
              number: 80
---
