# Usar a imagem base do Alpine Linux
FROM alpine:3.19

# Instalar Nginx, PHP-FPM e outras dependências
RUN apk add --no-cache nginx php php-fpm php-mysqli php-json php-opcache php-gd php-curl php-mbstring php-xml php-session php-fpm openrc

# Configurar o PHP-FPM
RUN mkdir -p /run/php && \
    sed -i "s|;daemonize = yes|daemonize = no|g" /etc/php82/php-fpm.conf && \
    sed -i "s|listen = 127.0.0.1:9000|listen = /run/php/php-fpm.sock|g" /etc/php82/php-fpm.d/www.conf && \
    sed -i "s|;listen.owner = nobody|listen.owner = nginx|g" /etc/php82/php-fpm.d/www.conf && \
    sed -i "s|;listen.group = nobody|listen.group = nginx|g" /etc/php82/php-fpm.d/www.conf && \
    sed -i "s|;listen.mode = 0660|listen.mode = 0660|g" /etc/php82/php-fpm.d/www.conf

# Configurar o Nginx
# RUN mkdir -p /run/nginx && 
   # rm /etc/nginx/conf.d/default.conf

COPY /files/nginx.conf /etc/nginx/nginx.conf
COPY /files/start.sh /opt/start.sh
# Copiar o código da aplicação PHP para o diretório web
COPY /files/index.html /var/www/html/
COPY /files/healthz.php /var/www/html/


# Definir permissões corretas
RUN chown -R nginx:nginx /var/www/html
COPY /files/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh
# Expor a porta 80
EXPOSE 80
USER root
# Definir o comando de inicialização
CMD ["/usr/local/bin/start.sh"]
# CMD ["nginx", "-g", "daemon off;"]