name: Docker Image CI

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "homolog" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker login -u ${{secrets.docker_user}} -p ${{secrets.docker_pass}}
    - run: pwd && ls 
    - run: cd docker-images && docker build . --file Dockerfile --tag ${{secrets.docker_user}}/app-demo:${{github.run_number}}
    - run: docker push ${{secrets.docker_user}}/app-demo:${{github.run_number}}
